steps:
  - name: ubuntu
    args:
      - echo
      - hello world
  - name: gcr.io/cloud-builders/gcloud
    args:
      - builds
      - submit
      - '--tag=gcr.io/epam-pankajjo/first-app'
      - '/workspace/docker/first-app/'

