steps:
  - name: ubuntu
    args:
      - echo
      - hello world
  - name: gcr.io/cloud-builders/gcloud
    args:
      - builds
      - submit
      - 'gcr.io/epam-pankajjo/first-app'
      - '.'

